//
// Created by nfriehs on 12/15/23.
//

#ifndef NF_TX_CORE_MAGICNUMBERS_H
#define NF_TX_CORE_MAGICNUMBERS_H

#define MAX_WALLETS 100
#define BIG_MAX_WALLETS 1000
#define MAX_STRING_LENGTH 100
#define MAX_DATE_LENGTH 40
#define MAX_TRANSACTIONS 1000

#endif //NF_TX_CORE_MAGICNUMBERS_H
